# application.yml (в git)
spring:
  config:
    import: optional:configserver:http://localhost:8888
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:}
    username: ${DB_USERNAME:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 300000

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

server:
  port: 8081  # Стандартный порт