spring:
  profiles:
    active: micro
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    org.flywaydb: DEBUG