services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ~/.ssh:/home/javauser/.ssh:ro
      - config-repo:/tmp/config-repo
    environment:
      - GIT_KNOWN_HOSTS=/home/javauser/.ssh/known_hosts
      - SPRING_PROFILES_ACTIVE=docker
      - GIT_SSH_COMMAND=ssh -i /home/javauser/.ssh/id_rsa -o StrictHostKeyChecking=no
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_GIT_URI:-git@github.com:hodkonem/mercury.git}
      - SERVER_PORT=${CONFIG_PORT:-8888}
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${SERVER_PORT}/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    hostname: eureka-server
    ports:
      - "${EUREKA_PORT:-8761}:${EUREKA_PORT:-8761}"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${EUREKA_PORT:-8761}/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=prod,micro
      - SERVER_PORT=${EUREKA_PORT:-8761}
      - EUREKA_INSTANCE_HOSTNAME=eureka-server

  auth-db:
    image: postgres:13
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  product-db:
    image: postgres:13
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - eureka-server
      - config-server
      - auth-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker,micro
      - SERVER_PORT=${AUTH_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL-AUTO=validate
      - SPRING_FLYWAY_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - microservices-net

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    depends_on:
      - eureka-server
      - config-server
      - product-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker,micro
      - SERVER_PORT=${PRODUCT_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL-AUTO=validate
      - SPRING_FLYWAY_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - microservices-net

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "${NOTIFICATION_PORT:-8083}:${NOTIFICATION_PORT:-8083}"
    depends_on:
      - eureka-server
      - config-server
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${NOTIFICATION_PORT:-8083}/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker,micro
      - SERVER_PORT=${NOTIFICATION_PORT:-8083}

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "${ORDER_PORT:-8084}:${ORDER_PORT:-8084}"
    depends_on:
      - eureka-server
      - config-server
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${ORDER_PORT:-8084}/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker,micro
      - SERVER_PORT=${ORDER_PORT:-8084}

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT:-8080}:${GATEWAY_PORT:-8080}"
    depends_on:
      - eureka-server
      - config-server
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${GATEWAY_PORT:-8080}/actuator/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker,micro
      - SERVER_PORT=${GATEWAY_PORT:-8080}

networks:
  microservices-net:
    driver: bridge

volumes:
  config-repo: