spring:
  application:
    name: gateway
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 5000
        max-attempts: 5

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,gateway