ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email TEXT CHECK (length(email) <= 255),
    ADD COLUMN IF NOT EXISTS phone TEXT CHECK (length(phone) <= 20),
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx ON users (email) WHERE email IS NOT NULL;