spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:8080}