INSERT INTO products(name, description, price, quantity)
VALUES ('Product 1',
        'Description 1',
        10,
        100),
       ('Product 2',
        'Description 2',
        20,
        200),
       ('Product 3',
        'Description 3',
        30,
        300),
       ('Product 4',
        'Description 4',
        40,
        400),
       ('Product 5',
        'Description 5',
        50,
        500),
       ('Product 6',
        'Description 6',
        60,
        600),
       ('Product 7',
        'Description 7',
        70,
        700),
       ('Product 8',
        'Description 8',
        80,
        800),
       ('Product 9',
        'Description 9',
        90,
        900),
       ('Product 10',
        'Description 10',
        100,
        1000);