spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:hodkonem/mercury.git
          basedir: /tmp/config-repo
          clone-on-start: true
          force-pull: true
          search-paths: '{application}'
          default-label: main
          ignore-local-ssh-settings: false
          timeout: 10
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    instance:
      preferIpAddress: false

server:
  port: 8888
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %C{1.} - %msg%n"