spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:hodkonem/mercury.git
          clone-on-start: true
          basedir: /tmp/config-repo
          force-pull: true
          default-label: main
          ignore-local-ssh-settings: false
          skip-ssl-validation: true
server:
  port: 8888
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %C{1.} - %msg%n"