spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-db:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

jwt:
  secret: ${JWT_SECRET}